/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sww_util */

#ifndef _Included_sww_util
#define _Included_sww_util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sww_util
 * Method:    get_enc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sww_util_get_1enc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
