/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cn09876_myapplication_MainActivity */

#ifndef _Included_com_example_cn09876_myapplication_MainActivity
#define _Included_com_example_cn09876_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cn09876_myapplication_MainActivity
 * Method:    get_pwd
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cn09876_myapplication_MainActivity_get_1pwd
  (JNIEnv *, jobject, jint );

#ifdef __cplusplus
}
#endif
#endif
